import json
from pathlib import Path

from sentence_transformers import CrossEncoder


# ============================================================
# CONFIGURATION
# ============================================================

MODEL_NAME = "BAAI/bge-reranker-base"

INPUT_PATH = (
    "output/retrieval_results.json"
)

OUTPUT_PATH = (
    "output/reranked_results.json"
)

TOP_K = 5


# ============================================================
# LOAD RETRIEVAL RESULTS
# ============================================================

def load_results(path: str) -> list[dict]:
    """
    Load the retrieval results generated by Step 6.
    """

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as file:

        return json.load(file)


# ============================================================
# LOAD RERANKER
# ============================================================

def load_reranker():
    """
    Load the BGE cross-encoder reranking model.
    """

    print(
        f"\nLoading reranker: {MODEL_NAME}"
    )

    model = CrossEncoder(
        MODEL_NAME
    )

    print(
        "Reranker loaded successfully."
    )

    return model


# ============================================================
# RERANK ONE REQUIREMENT
# ============================================================

def rerank_requirement(
    requirement: dict,
    model: CrossEncoder,
    top_k: int = TOP_K
) -> dict:
    """
    Rerank the retrieved test cases for one requirement.
    """

    requirement_text = (
        requirement["requirement_text"]
    )

    candidates = requirement.get(
        "candidates",
        []
    )

    if not candidates:

        return {
            **requirement,
            "reranked_candidates": []
        }

    # --------------------------------------------------------
    # Create requirement-test case pairs
    # --------------------------------------------------------

    pairs = []

    for candidate in candidates:

        test_case_text = (
            candidate["document"]
        )

        pairs.append(
            [
                requirement_text,
                test_case_text
            ]
        )

    # --------------------------------------------------------
    # Calculate reranking scores
    # --------------------------------------------------------

    scores = model.predict(
        pairs
    )

    # --------------------------------------------------------
    # Attach scores
    # --------------------------------------------------------

    reranked_candidates = []

    for candidate, score in zip(
        candidates,
        scores
    ):

        candidate_copy = (
            candidate.copy()
        )

        candidate_copy[
            "reranker_score"
        ] = round(
            float(score),
            4
        )

        reranked_candidates.append(
            candidate_copy
        )

    # --------------------------------------------------------
    # Sort by reranker score
    # --------------------------------------------------------

    reranked_candidates.sort(
        key=lambda x: x[
            "reranker_score"
        ],
        reverse=True
    )

    # --------------------------------------------------------
    # Keep top-K
    # --------------------------------------------------------

    reranked_candidates = (
        reranked_candidates[:top_k]
    )

    return {
        **requirement,

        "reranked_candidates":
            reranked_candidates
    }


# ============================================================
# RERANK ALL REQUIREMENTS
# ============================================================

def rerank_all(
    results: list[dict],
    model: CrossEncoder,
    top_k: int = TOP_K
) -> list[dict]:
    """
    Rerank candidates for every requirement.
    """

    reranked_results = []

    total = len(results)

    for index, requirement in enumerate(
        results,
        start=1
    ):

        print(
            f"Reranking "
            f"{index}/{total}: "
            f"{requirement['requirement_id']}"
        )

        result = rerank_requirement(
            requirement,
            model,
            top_k
        )

        reranked_results.append(
            result
        )

    return reranked_results


# ============================================================
# SAVE RESULTS
# ============================================================

def save_results(
    results: list[dict],
    path: str
):
    """
    Save reranked results to JSON.
    """

    output_path = Path(path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            results,
            file,
            indent=4,
            ensure_ascii=False
        )


# ============================================================
# DISPLAY SAMPLE RESULTS
# ============================================================

def display_sample(
    results: list[dict]
):
    """
    Display reranking results for the first requirement.
    """

    if not results:

        return

    first = results[0]

    print(
        "\n" + "=" * 80
    )

    print(
        f"REQUIREMENT: "
        f"{first['requirement_id']}"
    )

    print(
        "=" * 80
    )

    print(
        first["requirement_text"]
    )

    print(
        "\nRERANKED TEST CASES:"
    )

    print(
        "-" * 80
    )

    for rank, candidate in enumerate(
        first["reranked_candidates"],
        start=1
    ):

        print(
            f"\n{rank}. "
            f"{candidate['test_case_id']}"
        )

        print(
            f"Reranker score: "
            f"{candidate['reranker_score']}"
        )

        print(
            f"Original BGE similarity: "
            f"{candidate['similarity']}"
        )

        print(
            "\nTest Case:"
        )

        print(
            candidate["document"]
        )


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 80)
    print("CROSS-ENCODER RERANKING")
    print("=" * 80)

    # --------------------------------------------------------
    # Load retrieval results
    # --------------------------------------------------------

    print(
        "\nLoading retrieval results..."
    )

    results = load_results(
        INPUT_PATH
    )

    print(
        f"Loaded results for "
        f"{len(results)} requirements."
    )

    if not results:

        print(
            "No retrieval results found."
        )

        return

    # --------------------------------------------------------
    # Load reranker
    # --------------------------------------------------------

    model = load_reranker()

    # --------------------------------------------------------
    # Rerank
    # --------------------------------------------------------

    print(
        "\nStarting reranking..."
    )

    reranked_results = rerank_all(
        results,
        model,
        TOP_K
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    save_results(
        reranked_results,
        OUTPUT_PATH
    )

    # --------------------------------------------------------
    # Display sample
    # --------------------------------------------------------

    display_sample(
        reranked_results
    )

    # --------------------------------------------------------
    # Finished
    # --------------------------------------------------------

    print(
        "\n" + "=" * 80
    )

    print(
        "RERANKING COMPLETE"
    )

    print(
        "=" * 80
    )

    print(
        f"\nResults saved to:"
    )

    print(
        OUTPUT_PATH
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()